#pragma once


#include "irpdrainer.h"
#include "definitions.h"
#include <ntifs.h>


#define TERMINATE_PROCESS CTL_CODE(FILE_DEVICE_UNKNOWN,0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define GET_EPROCESS CTL_CODE(FILE_DEVICE_UNKNOWN,0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define PRINT_ALL_PROCESSES CTL_CODE(FILE_DEVICE_UNKNOWN,0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define HIDE_PROCESS CTL_CODE(FILE_DEVICE_UNKNOWN,0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define UNHIDE_PROCESS CTL_CODE(FILE_DEVICE_UNKNOWN,0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define PRINT_ALL_THREADS CTL_CODE(FILE_DEVICE_UNKNOWN,0x806, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define PRINT_ALL_DLLS CTL_CODE(FILE_DEVICE_UNKNOWN,0x807, METHOD_BUFFERED, FILE_ANY_ACCESS)


typedef struct {
	LONGLONG eprocess;
}datatosend, * pdatatosend;


typedef struct {
	UINT32 pid;
}PROCESS_ID, * PPROCESS_ID;



extern "C" NTSTATUS devicecontrolhandler(PDEVICE_OBJECT fdo, PIRP irp);


NTSTATUS TerminateProcess(UINT32 pid);

